#!/bin/bash

#HIGHER LEVEL PARAMS
export r=1 #RUN NUMBER INDEX ABSOLUTE ACROSS SIM SET
export i=10 #NUMBER OF RUNS PER PARAMETER POINT

#STATICs
export c=0.95 #CLAMP FOR LENS
export n=400

#K=12
export k=12

#Ps
export p=0.00 
source LoopSHELL

export p=0.01 
source LoopSHELL

export p=0.05 
source LoopSHELL

export p=0.10 
source LoopSHELL

export p=0.15 
source LoopSHELL

export p=0.20 
source LoopSHELL

export p=0.25 
source LoopSHELL

export p=0.50 
source LoopSHELL

export p=0.75 
source LoopSHELL

export p=1.00 
source LoopSHELL

#K=50
export k=50

#Ps
export p=0.00 
source LoopSHELL

export p=0.01 
source LoopSHELL

export p=0.05 
source LoopSHELL

export p=0.10 
source LoopSHELL

export p=0.15 
source LoopSHELL

export p=0.20 
source LoopSHELL

export p=0.25 
source LoopSHELL

export p=0.50 
source LoopSHELL

export p=0.75 
source LoopSHELL

export p=1.00 
source LoopSHELL

#K=69
export k=69

#Ps
export p=0.00 
source LoopSHELL

export p=0.01 
source LoopSHELL

export p=0.05 
source LoopSHELL

export p=0.10 
source LoopSHELL

export p=0.15 
source LoopSHELL

export p=0.20 
source LoopSHELL

export p=0.25 
source LoopSHELL

export p=0.50 
source LoopSHELL

export p=0.75 
source LoopSHELL

export p=1.00 
source LoopSHELL

#K=88
export k=88

#Ps
export p=0.00 
source LoopSHELL

export p=0.01 
source LoopSHELL

export p=0.05 
source LoopSHELL

export p=0.10 
source LoopSHELL

export p=0.15 
source LoopSHELL

export p=0.20 
source LoopSHELL

export p=0.25 
source LoopSHELL

export p=0.50 
source LoopSHELL

export p=0.75 
source LoopSHELL

export p=1.00 
source LoopSHELL

#K=107
export k=107

#Ps
export p=0.00 
source LoopSHELL

export p=0.01 
source LoopSHELL

export p=0.05 
source LoopSHELL

export p=0.10 
source LoopSHELL

export p=0.15 
source LoopSHELL

export p=0.20 
source LoopSHELL

export p=0.25 
source LoopSHELL

export p=0.50 
source LoopSHELL

export p=0.75 
source LoopSHELL

export p=1.00 
source LoopSHELL

#K=126
export k=126

#Ps
export p=0.00 
source LoopSHELL

export p=0.01 
source LoopSHELL

export p=0.05 
source LoopSHELL

export p=0.10 
source LoopSHELL

export p=0.15 
source LoopSHELL

export p=0.20 
source LoopSHELL

export p=0.25 
source LoopSHELL

export p=0.50 
source LoopSHELL

export p=0.75 
source LoopSHELL

export p=1.00 
source LoopSHELL

#K=145
export k=145

#Ps
export p=0.00 
source LoopSHELL

export p=0.01 
source LoopSHELL

export p=0.05 
source LoopSHELL

export p=0.10 
source LoopSHELL

export p=0.15 
source LoopSHELL

export p=0.20 
source LoopSHELL

export p=0.25 
source LoopSHELL

export p=0.50 
source LoopSHELL

export p=0.75 
source LoopSHELL

export p=1.00 
source LoopSHELL

#K=164
export k=164

#Ps
export p=0.00 
source LoopSHELL

export p=0.01 
source LoopSHELL

export p=0.05 
source LoopSHELL

export p=0.10 
source LoopSHELL

export p=0.15 
source LoopSHELL

export p=0.20 
source LoopSHELL

export p=0.25 
source LoopSHELL

export p=0.50 
source LoopSHELL

export p=0.75 
source LoopSHELL

export p=1.00 
source LoopSHELL

#K=183
export k=183

#Ps
export p=0.00 
source LoopSHELL

export p=0.01 
source LoopSHELL

export p=0.05 
source LoopSHELL

export p=0.10 
source LoopSHELL

export p=0.15 
source LoopSHELL

export p=0.20 
source LoopSHELL

export p=0.25 
source LoopSHELL

export p=0.50 
source LoopSHELL

export p=0.75 
source LoopSHELL

export p=1.00 
source LoopSHELL

#K=202
export k=202

#Ps
export p=0.00 
source LoopSHELL

export p=0.01 
source LoopSHELL

export p=0.05 
source LoopSHELL

export p=0.10 
source LoopSHELL

export p=0.15 
source LoopSHELL

export p=0.20 
source LoopSHELL

export p=0.25 
source LoopSHELL

export p=0.50 
source LoopSHELL

export p=0.75 
source LoopSHELL

export p=1.00 
source LoopSHELL

#CLEAN UP
chmod a-w test.out
mv goodness.out ../Analy
mv outputs.out ../Analy

#EOF
